[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first'

[profile.default]
solc = '0.8.14'
src = 'solidity'
out = 'out'
libs = ['lib']
